const IngredientsData = [
	{
		id: "0",
		name: "Beetle Scuttle",
		effect1: "Breach",
		effect2: "Increase Armor",
		effect3: "Protection",
		effect4: "Vitality",
		src: "/images/Beetle_Scuttle.png",
	},
	{
		id: "1",
		name: "Blessed Thistle",
		effect1: "Restore Stamina",
		effect2: "Increase Weapon Power",
		effect3: "Ravage Health",
		effect4: "Speed",
		src: "/images/Blessed_Thistle.png",
	},
	{
		id: "2",
		name: "Blue Entoloma",
		effect1: "Ravage Magicka",
		effect2: "Cowardice",
		effect3: "Restore Health",
		effect4: "Invisible",
		src: "/images/Blue_Entoloma.png",
	},
	{
		id: "3",
		name: "Bugloss",
		effect1: "Increase Spell Resist",
		effect2: "Restore Health",
		effect3: "Cowardice",
		effect4: "Restore Magicka",
		src: "/images/Bugloss.png",
	},
	{
		id: "4",
		name: "Butterfly Wing",
		effect1: "Restore Health",
		effect2: "Lingering Health",
		effect3: "Uncertainty",
		effect4: "Vitality",
		src: "/images/Butterfly_Wing.png",
	},
	{
		id: "5",
		name: "Chaurus Egg",
		effect1: "Timidity",
		effect2: "Ravage Magicka",
		effect3: "Restore Stamina",
		effect4: "Detection",
		src: "/images/Chaurus_Egg.png",
	},
	{
		id: "6",
		name: "Clam Gall",
		effect1: "Increase Spell Resist",
		effect2: "Hindrance",
		effect3: "Vulnerability",
		effect4: "Defile",
		src: "/images/Clam_Gall.png",
	},
	{
		id: "7",
		name: "Columbine",
		effect1: "Restore Health",
		effect2: "Restore Magicka",
		effect3: "Restore Stamina",
		effect4: "Unstoppable",
		src: "/images/Columbine.png",
	},
	{
		id: "8",
		name: "Corn Flower",
		effect1: "Restore Magicka",
		effect2: "Increase Spell Power",
		effect3: "Ravage Health",
		effect4: "Detection",
		src: "/images/Corn_Flower.png",
	},
	{
		id: "9",
		name: "Crimson Nirnroot",
		effect1: "Timidity",
		effect2: "Spell Critical",
		effect3: "Gradual Ravage Health",
		effect4: "Restore Health",
		src: "/images/Crimson_Nirnroot.png",
	},
	{
		id: "10",
		name: "Dragon's Bile",
		effect1: "Heroism",
		effect2: "Vulnerability",
		effect3: "Invisible",
		effect4: "Vitality",
		src: "/images/Dragons_Bile.png",
	},
	{
		id: "11",
		name: "Dragon's Blood",
		effect1: "Lingering Health",
		effect2: "Restore Stamina",
		effect3: "Heroism",
		effect4: "Defile",
		src: "/images/Dragons_Blood.png",
	},
	{
		id: "12",
		name: "Dragon Rheum",
		effect1: "Restore Magicka",
		effect2: "Enervation",
		effect3: "Heroism",
		effect4: "Speed",
		src: "/images/Dragon_Rheum.png",
	},
	{
		id: "13",
		name: "Dragonthorn",
		effect1: "Increase Weapon Power",
		effect2: "Restore Stamina",
		effect3: "Fracture",
		effect4: "Weapon Critical",
		src: "/images/Dragonthorn.png",
	},
	{
		id: "14",
		name: "Emetic Russula",
		effect1: "Ravage Health",
		effect2: "Ravage Magicka",
		effect3: "Ravage Stamina",
		effect4: " Entrapment",
		src: "/images/Emetic_Russula.png",
	},
	{
		id: "15",
		name: "Fleshfly Larva",
		effect1: "Ravage Stamina",
		effect2: "Vulnerability",
		effect3: "Gradual Ravage Health",
		effect4: "Vitality",
		src: "/images/Fleshfly_Larva.png",
	},
	{
		id: "16",
		name: "Imp Stool",
		effect1: "Maim",
		effect2: "Ravage Stamina",
		effect3: "Increase Armor",
		effect4: "Enervation",
		src: "/images/Imp_Stool.png",
	},
	{
		id: "17",
		name: "Lady's Smock",
		effect1: "Increase Spell Power",
		effect2: "Restore Magicka",
		effect3: "Breach",
		effect4: "Spell Critical",
		src: "/images/Ladys_Smock.png",
	},
	{
		id: "18",
		name: "Luminous Russula",
		effect1: "Ravage Stamina",
		effect2: "Maim",
		effect3: "Restore Health",
		effect4: "Hindrance",
		src: "/images/Luminous_Russula.png",
	},
	{
		id: "19",
		name: "Mountain Flower",
		effect1: "Increase Armor",
		effect2: "Restore Health",
		effect3: "Maim",
		effect4: "Restore Stamina",
		src: "/images/Mountain_Flower.png",
	},
	{
		id: "20",
		name: "Mudcrab Chitin",
		effect1: "Increase Spell Resist",
		effect2: "Increase Armor",
		effect3: "Protection",
		effect4: "Defile",
		src: "/images/Mudcrab_Chitin.png",
	},
	{
		id: "21",
		name: "Namira's Rot",
		effect1: "Spell Critical",
		effect2: "Speed",
		effect3: "Invisible",
		effect4: "Unstoppable",
		src: "/images/Namiras_Rot.png",
	},
	{
		id: "22",
		name: "Nightshade",
		effect1: "Ravage Health",
		effect2: "Protection",
		effect3: "Gradual Ravage Health",
		effect4: "Defile",
		src: "/images/Nightshade.png",
	},
	{
		id: "23",
		name: "Nirnroot",
		effect1: "Ravage Health",
		effect2: "Uncertainty",
		effect3: "Enervation",
		effect4: "Invisible",
		src: "/images/Nirnroot.png",
	},
	{
		id: "24",
		name: "Powdered Mother of Pearl",
		effect1: "Lingering Health",
		effect2: "Speed",
		effect3: "Vitality",
		effect4: "Protection",
		src: "/images/Powdered_Mother_of_Pearl.png",
	},
	{
		id: "25",
		name: "Scrib Jelly",
		effect1: "Ravage Magicka",
		effect2: "Speed",
		effect3: "Vulnerability",
		effect4: "Lingering Health",
		src: "/images/Scrib_Jelly.png",
	},
	{
		id: "26",
		name: "Spider Egg",
		effect1: "Hindrance",
		effect2: "Invisible",
		effect3: "Lingering Health",
		effect4: "Defile",
		src: "/images/Spider_egg.png",
	},
	{
		id: "27",
		name: "Stinkhorn",
		effect1: "Fracture",
		effect2: "Ravage Health",
		effect3: "Increase Weapon Power",
		effect4: "Ravage Stamina",
		src: "/images/Stinkhorn.png",
	},
	{
		id: "28",
		name: "Torchbug Thorax",
		effect1: "Fracture",
		effect2: "Enervation",
		effect3: "Detection",
		effect4: "Vitality",
		src: "/images/Torchbug_Thorax.png",
	},
	{
		id: "29",
		name: "Vile Coagulant",
		effect1: "Timidity",
		effect2: "Ravage Health",
		effect3: "Restore Magicka",
		effect4: "Protection",
		src: "/images/Vile_Coagulant.png",
	},
	{
		id: "30",
		name: "Violet Coprinus",
		effect1: "Breach",
		effect2: "Ravage Health",
		effect3: "Increase Spell Power",
		effect4: "Ravage Magicka",
		src: "/images/Violet_Coprinus.png",
	},
	{
		id: "31",
		name: "Water Hyacinth",
		effect1: "Restore Health",
		effect2: "Spell Critical",
		effect3: "Weapon Critical",
		effect4: "Entrapment",
		src: "/images/Water_Hyacinth.png",
	},
	{
		id: "32",
		name: "White Cap",
		effect1: "Cowardice",
		effect2: "Ravage Magicka",
		effect3: "Increase Spell Resist",
		effect4: "Detection",
		src: "/images/White_Cap.png",
	},
	{
		id: "33",
		name: "Wormwood",
		effect1: "Weapon Critical",
		effect2: "Hindrance",
		effect3: "Detection",
		effect4: "Unstoppable",
		src: "/images/Wormwood.png",
	}
];

export default IngredientsData;